### ISSUE TITLE
Problem with node 10

### ISSUE THREAD

**Issue by GuiHarrison** [html5blank/html5blank#205]
Hi! I'm using node.js 10.13.0 and when I install everything and run ````gulp watch```` I get the following error:

	gulp[#####]: src\node_contextify.cc:628: Assertion `args[1]->IsString()' failed.
	 1: 00007FF6F96FECE5
	 2: 00007FF6F96D8196
	 3: 00007FF6F96D8261
	 4: 00007FF6F96AB56A
	 5: 00007FF6F9F02E52
	 6: 00007FF6F9F03FD8
	 7: 00007FF6F9F0330D
	 8: 00007FF6F9F0322B
	 9: 00000338D4D5C5C1

I've seen that if you do ````npm i natives```` you could solve that problem but when I do that, I get a different problem:

	[17:36:21] Using gulpfile C:\..my-site..\gulpfile.js
	[17:36:21] Starting 'template'...
	`template` task run in `development` environment
	[17:36:21] Starting 'sass'...
	[17:36:21] Starting 'jshint'...
	[17:36:21] Starting 'modernizr'...
	[17:36:22] Finished 'modernizr' after 375 ms
	[17:36:22] Starting 'jquery'...
	[17:36:22] Starting 'normalize'...
	{ Error: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
	    at maybeCallback (fs.js:129:9)

	    at C:\..my-site..\node_modules\requirejs\bin\r.js:30099:19
	    at C:\..my-site..\node_modules\requirejs\bin\r.js:3081:39
	    at C:\..my-site..\node_modules\requirejs\bin\r.js:3021:25
	    at Function.prim.nextTick (C:\..my-site..\node_modules\requirejs\bin\r.js:29929:9)
	    at Object.errback (C:\..my-site..\node_modules\requirejs\bin\r.js:3020:26)
	    at Object.callback (C:\..my-site..\node_modules\requirejs\bin\r.js:3006:23)
	    at Object.then (C:\..my-site..\node_modules\requirejs\bin\r.js:3060:23)
	    at build (C:\..my-site..\node_modules\requirejs\bin\r.js:30056:12)
	    at runBuild (C:\..my-site..\node_modules\requirejs\bin\r.js:32006:17)
	    at Object.execCb (C:\..my-site..\node_modules\requirejs\bin\r.js:1941:33)
	  originalError:
	   TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
	       at maybeCallback (fs.js:129:9)
	       at Object.writeFile (fs.js:1156:14)
	       at C:\..my-site..\gulpfile.js:130:7
	       at Object.requireConfig.out (C:\..my-site..\node_modules\modernizr\lib\build.js:97:7)
	       at C:\..my-site..\node_modules\requirejs\bin\r.js:30591:24
	       at C:\..my-site..\node_modules\requirejs\bin\r.js:3063:37
	       at C:\..my-site..\node_modules\requirejs\bin\r.js:3011:25
	       at Function.prim.nextTick (C:\..my-site..\node_modules\requirejs\bin\r.js:29929:9)
	       at Object.callback (C:\..my-site..\node_modules\requirejs\bin\r.js:3010:26)
	       at Object.then (C:\..my-site..\node_modules\requirejs\bin\r.js:3060:23) }

Any idea how to mitigate this? Is the only solution a downgrade of node.js or is it possible to use a different version of a dependency?

Thanks!

**Comment by arbitrarily** [comment]
+1

**Comment by HumanSprout** [comment]
Have you tried fulfilling the "required optional" callback param with a generic function? I've received a similar error and just putting in `()=>{}` is enough to shut it up

**Comment by GuiHarrison** [comment]
Sorry, @HumanSprout I didn't get how to change the callback that way. I did just went and commented out the line 3051 top 3106 of r.js and it worked (with some complaining).

**Comment by ricardogouveia3** [comment]
Someone have worked this out? Stuck with it here

**Comment by thetwosents** [comment]
Yep, unusable for me also...

**Comment by krupalpatel92** [comment]
Nothing to do too much here. Just need to add missing param for **fs.writeFile** as callback function.

**gulpfile.js:129 OLD**
```
modernizr.build(config, function(code) {
      fs.writeFile("./src/js/lib/modernizr.js", code);
});
```

**gulpfile.js:129 NEW**
```
modernizr.build(config, function(code) {
       fs.writeFile("./src/js/lib/modernizr.js", code, {}, function() {
       });
});

```


**package.json new versions**
```
{
  "dependencies": {
    "mkdirp": "^0.5.1",
    "modernizr": "^3.7.1",
    "normalize.css": "^7.0.0",
    "npm": "^5.10.0"
  },
  "devDependencies": {
    "del": "^3.0.0",
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^4.1.0",
    "gulp-concat": "^2.6.1",
    "gulp-csso": "^3.0.1",
    "gulp-jshint": "^2.1.0",
    "gulp-livereload": "^3.8.1",
    "gulp-load-plugins": "^1.6.0",
    "gulp-sass": "^3.2.1",
    "gulp-sourcemaps": "^2.6.5",
    "gulp-template": "^5.0.0",
    "gulp-uglify": "^3.0.2",
    "jquery": "^3.4.1",
    "jshint": "^2.10.2",
    "jshint-stylish": "^2.2.1"
  },
  "engines": {
    "node": ">=0.10.0"
  }
}
```
