### ISSUE TITLE
error while installing

### ISSUE THREAD

**Issue by jucajuca** [html5blank/html5blank#229]
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/code/html5blank/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-7634-generic
gyp ERR! command "/usr/bin/node" "/code/html5blank/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /code/html5blank/node_modules/node-sass
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jccb/.npm/_logs/2020-08-18T18_57_21_607Z-debug.log

**Comment by rikvdh** [comment]
The current version of node-sass in package-lock.json is set to v4.7.2, which is not supported on NodeJS 10+. You can update node-sass to v4.14 with: `npm install --save node-sass@v4.14.1`
Which passes installation and you can continue.

**Comment by fguillen** [comment]
I have tried: 

> npm install --save node-sass@v4.14.1 
> npm install --save --save-exact node-sass@v4.14.1 
> npm install --save-dev node-sass@v4.14.1   

Nothing works :/. I keep having the same (or similar) error: 

```
4171 verbose stack Error: node-sass@4.7.2 postinstall: `node scripts/build.js`
4171 verbose stack Exit status 1
4171 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
4171 verbose stack     at EventEmitter.emit (events.js:315:20)
4171 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
4171 verbose stack     at ChildProcess.emit (events.js:315:20)
4171 verbose stack     at maybeClose (internal/child_process.js:1051:16)
4171 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
4172 verbose pkgid node-sass@4.7.2
4173 verbose cwd /Users/fernando.guillen/Sites/wordpress_1/wp-content/themes/html5blank
4174 verbose Darwin 19.5.0
4175 verbose argv "/usr/local/Cellar/node/14.4.0/bin/node" "/usr/local/bin/npm" "install" "--save" "node-sass@v4.14.1"
4176 verbose node v14.4.0
4177 verbose npm  v6.14.4
4178 error code ELIFECYCLE
4179 error errno 1
4180 error node-sass@4.7.2 postinstall: `node scripts/build.js`
4180 error Exit status 1
4181 error Failed at the node-sass@4.7.2 postinstall script.
4181 error This is probably not a problem with npm. There is likely additional logging output above.
4182 verbose exit [ 1, true ]
```

**Comment by fguillen** [comment]
I did a lot of things but I think this made the trick: 

> npm install --save gulp-sass@3.2.1
